// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-09-05 19:29:33.7553647 +0800 CST m=+0.039893501

package docs

import (
	"fmt"
	"github.com/swaggo/swag"
	"io/ioutil"
)

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0.0",
	Host:        "",
	BasePath:    "/api/v1/",
	Schemes:     []string{},
	Title:       "i2推手管理平台",
	Description: "i2推手管理平台接口",
}

type s struct{}

func (s *s) ReadDoc(project string) string {
	swaggerjsonfile :=  "files/" + project + ".json"
	fmt.Println("------>project file", swaggerjsonfile)
	bytess, err := ioutil.ReadFile(swaggerjsonfile)
	if err != nil{
		fmt.Println(err.Error())
		return ""
	}else{
		return string(bytess)
	}
}

func init() {
	swag.Register(swag.Name, &s{})
}
