basePath: /api/v1/
definitions:
  models.App:
    properties:
      id:
        description: |-
          the id for this app

          required: true
        type: string
    type: object
info:
  contact: {}
  description: i2推手管理平台接口
  license: {}
  title: i2推手管理平台
  version: 1.0.0
paths:
  /:
    post:
      description: create App
      parameters:
      - description: body for App content
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.App'
          type: object
      responses:
        "201":
          description: Created
          schema:
            type: int
        "400":
          description: Bad Request
          schema:
            type: body
  /c/app:
    post:
      description: create App
      parameters:
      - description: body for App content
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.App'
          type: object
      responses:
        "201":
          description: Created
          schema:
            type: int
        "400":
          description: Bad Request
          schema:
            type: body
  /record/{some_id}:
    get:
      consumes:
      - application/json
      description: get record by ID
      parameters:
      - description: userId
        in: path
        name: some_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
swagger: "2.0"
